baseurl = "https://eltonminetto.net/"
DefaultContentLanguage = "pt-br"
# DefaultContentLanguage = "en"
# languageCode = "en-us"
title = "Elton Minetto"
theme = "paper"
pygmentsuseclasses = true
PygmentsCodeFences = true
disqusShortname = "elton-minetto"
googleAnalytics = "UA-584603-1"
[Author]
    name = "Elton Minetto"
    email = "eminetto@gmail.com"
    github = "eminetto"
    twitter = "eminetto"
    linkedin = "in/eminetto"

[languages]
  [languages.en]
    # [Params]
    # logo = "img/avatar-icon.png"
    subtitle = "Developer, teacher, speaker and writer"
    [[menu.en]]
        name = "Talks"
        url = "/talks/"
        weight = 1
    [[menu.en]]
        name = "About"
        url = "/about/"
        weight = 5
  [languages.pt-br]
    # [Params]
    # logo = "img/avatar-icon.png"
    subtitle = "Desenvolvedor, professor, palestrante e escritor"

    [[menu.pt]]
        name = "Livros"
        url = "https://leanpub.com/u/eminetto"
        weight = 1

    [[menu.pt]]
        name = "Palestras"
        url = "/talks/"
        weight = 2
    [[menu.pt]]
        name = "A semana PHP"
        url = "http://asemanaphp.com.br"
        weight = 3
    [[menu.pt]]
        name = "A semana Go"
        url = "http://asemanago.com.br"
        weight = 4
    [[menu.pt]]
        name = "Sobre"
        url = "/sobre/"
        weight = 5