---
- name: Deploy eltonminetto.net
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Deploy para S3
      s3:
        bucket=teste-hugo
        region=sa-east-1
        aws_access_key=AKIAJBR6ZS7QPR2D67XA
        aws_secret_key=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
        object={{ item }}
        src={{ item }}
        mode=create
      with_fileglob:
        - public/*
